### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [Cilenco/skipTrackLongPressVolume#14]
Hi,

What's the license of this project?

If it's something open-source like the GNU GPL v3 license, we could try to add it to F-Droid if you're ok.

**Comment by Incineroar** [comment]
Wondering the same too. I made some changes that improve compatibility and people are wanting a precompiled build. Am I allowed to redistribute built copies of this?

**Comment by Cilenco** [comment]
Have added it. Its und MIT license.
