### ISSUE TITLE
Parsing package error

### ISSUE THREAD

**Issue by sandaldom** [Cilenco/skipTrackLongPressVolume#15]
Hi !
I'd love to use this app, "skip track". I hope to use it skip tracks over "mx player" and also to scroll web pages text over "chrome".

I download the apk file without errors. But when I click it to install the app it appears the message "Parsing package error".

I have deactivated "Play protect" and "Install Apps of unknown sources" is checked ON.

I am using Android 7.0 on my Huawei P9 EVA-L09 no root.

Thanks for helping me.

**Comment by Cilenco** [comment]
The app only works on Android Oreo (8.0+) sorry!
