### ISSUE TITLE
Any guide regarding how to build it?

### ISSUE THREAD

**Issue by MrBIMC** [Cilenco/skipTrackLongPressVolume#4]
```java
/**  
     * Listens the volume key long-presses.  
     * @hide  
     */  
    @SystemApi  
    public interface OnVolumeKeyLongPressListener {  
        /**  
         * Called when the volume key is long-pressed.  
         * <p>This will be called for both down and up events.  
         */  
        void onVolumeKeyLongPress(KeyEvent event);  
    }

```
That interface is hidden inside the MediaSessionManager and thus I can't manage to build this app inside the android studio. Is there a way to build that stuff easily?

**Comment by indianpoptart** [comment]
Check the gradle version and make sure you are using the hidden-api

[android-hidden-api - Issue 46](https://github.com/anggrayudi/android-hidden-api/issues/46)

**Comment by Cilenco** [comment]
Also check out this README [section](https://github.com/Cilenco/skipTrackLongPressVolume#for-developers)
