### ISSUE TITLE
"There Was A Problem Parsing The Package" error. 

### ISSUE THREAD

**Issue by YouDontCare** [Cilenco/skipTrackLongPressVolume#9]
Just that. Can't get it to install. Gives me the parsing error, which according to Google means "corrupted apk file". 

Permission to install unofficial apps has been granted, and USB debugging is on. Anything else I should try? Or should I just pack in?

**Comment by indianpoptart** [comment]
What OS version are you on?

**Comment by YouDontCare** [comment]
6.0 If that's sufficient info. If not, I can get a screengrab of the 'about the phone' page.

**Comment by Cilenco** [comment]
The app is for 8.0+ devices only

**Comment by YouDontCare** [comment]
Lawl okay, nevermind me then!
